version: '3.1'

services:

  frontend:
    build:
      dockerfile: ./Dockerfile
      context: ../frontend
    volumes:
      - ../frontend/src:/frontend/src
    stdin_open: true
    ports:
      - "3000:3000"

  backend:
    build:
      dockerfile: ./Dockerfile
      context: ../backend
    volumes:
      - ../backend/src:/backend/src
    ports:
      - "3001:3001"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 111
      POSTGRES_USER: admin
      POSTGRES_DB: mydb
